#!/bin/bash

echo ""
echo "🚀 DEPLOY AUTOMÁTICO INICIADO NO VERCEL"
echo "========================================"
echo ""
echo "✅ Commit: e8a38c4"
echo "✅ Push para GitHub: Sucesso"
echo "✅ Vercel vai detectar push e iniciar build"
echo ""
echo "⏳ Aguardando build do Vercel..."
echo ""
echo "📋 MONITORAR DEPLOY:"
echo "   https://vercel.com/subrevivas-projects/v0-remix-of-untitled-chat-liard-one/deployments"
echo ""
echo "⏱️  Tempo estimado: 2-3 minutos"
echo ""
echo "✅ APÓS DEPLOY COMPLETAR:"
echo "   1. Abrir: https://v0-remix-of-untitled-chat-liard-one.vercel.app/login"
echo "   2. Modo incognito (limpar cache)"
echo "   3. Login: estraca@2lados.pt / lumiarbcv"
echo "   4. Esperado: Redirect para /chat (SEM erro de permissões)"
echo ""
echo "🔍 SE AINDA FALHAR:"
echo "   1. F12 → Console → Ver erro exato"
echo "   2. F12 → Network → Ver qual request falha (400/401)"
echo "   3. Copiar mensagem de erro completa"
echo ""
echo "📊 LOGS DO VERCEL:"
echo "   Deployments → [último] → View Function Logs"
echo ""
