#!/bin/bash

echo "🔴 ATENÇÃO: API Key do Google foi BLOQUEADA!"
echo ""
echo "A API Key atual foi reportada como LEAKED e está bloqueada pelo Google."
echo ""
echo "📋 Passos para corrigir:"
echo ""
echo "1. Crie nova API Key: https://aistudio.google.com/apikey"
echo "2. Edite .env.local e substitua a linha:"
echo "   GOOGLE_API_KEY=AIzaSyByQnR9qMgZTi_kUGvx9u--TtTSV4zP6G8"
echo "   por sua nova key"
echo ""
echo "3. Atualize na Vercel também:"
echo "   https://vercel.com/subreviva/dua-premium/settings/environment-variables"
echo ""
echo "4. Teste localmente:"
echo "   node test-imagen-real.mjs"
echo ""
echo "5. Delete a key antiga do Google AI Studio"
echo ""
echo "📄 Documentação completa: SOLUCAO_API_KEY_LEAKED.md"
echo ""
