#!/bin/bash

echo "🔴 AÇÃO URGENTE NECESSÁRIA!"
echo ""
echo "A API Key tanto local quanto na Vercel está BLOQUEADA pelo Google."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 PASSOS OBRIGATÓRIOS (não posso fazer isso por você):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Criar Nova API Key:"
echo "    → Abra: https://aistudio.google.com/apikey"
echo "    → Clique em 'Create API Key'"
echo "    → Copie a key gerada"
echo ""
echo "2️⃣  Atualizar .env.local (ESTE ARQUIVO):"
echo "    → Edite: .env.local"
echo "    → Linha 1: GOOGLE_API_KEY=SUA_NOVA_KEY_AQUI"
echo ""
echo "3️⃣  Atualizar Vercel (PRODUÇÃO):"
echo "    → Abra: https://vercel.com/settings/environment-variables"
echo "    → Edite GOOGLE_API_KEY"
echo "    → Cole a nova key"
echo "    → Salve"
echo ""
echo "4️⃣  Testar:"
echo "    → Execute: node test-imagen-real.mjs"
echo ""
echo "5️⃣  Deploy:"
echo "    → Execute: git commit --allow-empty -m 'new api key' && git push"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  IMPORTANTE: Sem uma nova API Key, NADA funcionará!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❓ Por que isso aconteceu?"
echo "   A API Key AIzaSyByQnR9qMgZTi_kUGvx9u--TtTSV4zP6G8"
echo "   foi exposta publicamente e o Google a bloqueou."
echo ""
echo "🛡️  Como evitar no futuro?"
echo "   ✅ NUNCA commite .env.local"
echo "   ✅ NUNCA use NEXT_PUBLIC_ em keys sensíveis"
echo "   ✅ Mantenha keys apenas server-side"
echo ""

# Verificar se .env.local está no .gitignore
if grep -q "^\.env\.local$" .gitignore 2>/dev/null; then
  echo "✅ .env.local está no .gitignore (seguro)"
else
  echo "⚠️  ADICIONE .env.local ao .gitignore!"
  echo ".env.local" >> .gitignore
fi

echo ""
echo "📄 Documentação completa: SOLUCAO_API_KEY_LEAKED.md"
echo ""
