-- ══════════════════════════════════════════════════════════════
-- 🎫 170 CÓDIGOS DE ACESSO EXCLUSIVOS - DUA IA
-- ══════════════════════════════════════════════════════════════
-- Data: 07/11/2025
-- Total: 170 códigos únicos
-- Uso: Executar no Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════

-- 1. Limpar códigos antigos (opcional)
-- DELETE FROM public.invite_codes WHERE active = true;

-- 2. Inserir 170 códigos exclusivos
INSERT INTO public.invite_codes (code, active, used_by, created_at)
VALUES
  ('DUA-05I5-LQG', true, NULL, NOW()),
  ('DUA-0880-0YO', true, NULL, NOW()),
  ('DUA-09A1-3K0', true, NULL, NOW()),
  ('DUA-0A98-EMT', true, NULL, NOW()),
  ('DUA-0EO0-TYC', true, NULL, NOW()),
  ('DUA-0JV0-IW1', true, NULL, NOW()),
  ('DUA-0K94-E00', true, NULL, NOW()),
  ('DUA-0QTO-Q30', true, NULL, NOW()),
  ('DUA-1BDU-LTE', true, NULL, NOW()),
  ('DUA-1ZWK-3XV', true, NULL, NOW()),
  ('DUA-2SIV-WJN', true, NULL, NOW()),
  ('DUA-2X8J-92Y', true, NULL, NOW()),
  ('DUA-2ZCS-IPX', true, NULL, NOW()),
  ('DUA-3AX2-XFY', true, NULL, NOW()),
  ('DUA-3GW1-GQ4', true, NULL, NOW()),
  ('DUA-3JE9-H8Z', true, NULL, NOW()),
  ('DUA-3OBG-IO4', true, NULL, NOW()),
  ('DUA-4F27-EGY', true, NULL, NOW()),
  ('DUA-4IUK-2I6', true, NULL, NOW()),
  ('DUA-4V02-XV2', true, NULL, NOW()),
  ('DUA-4V9Z-447', true, NULL, NOW()),
  ('DUA-56XV-13W', true, NULL, NOW()),
  ('DUA-5BTM-U8D', true, NULL, NOW()),
  ('DUA-5M2C-KHG', true, NULL, NOW()),
  ('DUA-5U42-H84', true, NULL, NOW()),
  ('DUA-5UU7-LXH', true, NULL, NOW()),
  ('DUA-6252-ISA', true, NULL, NOW()),
  ('DUA-64Y2-RR7', true, NULL, NOW()),
  ('DUA-65JO-5D0', true, NULL, NOW()),
  ('DUA-66NN-K5B', true, NULL, NOW()),
  ('DUA-6700-Y1L', true, NULL, NOW()),
  ('DUA-6BVI-1XX', true, NULL, NOW()),
  ('DUA-6HM9-P0T', true, NULL, NOW()),
  ('DUA-6UHY-PQM', true, NULL, NOW()),
  ('DUA-70LZ-1GS', true, NULL, NOW()),
  ('DUA-7JCW-ZQN', true, NULL, NOW()),
  ('DUA-7VMG-Q25', true, NULL, NOW()),
  ('DUA-8BHC-KZZ', true, NULL, NOW()),
  ('DUA-8CH1-07C', true, NULL, NOW()),
  ('DUA-8ZWR-I3V', true, NULL, NOW()),
  ('DUA-9TT3-G76', true, NULL, NOW()),
  ('DUA-9XMQ-6DY', true, NULL, NOW()),
  ('DUA-A0OH-JGW', true, NULL, NOW()),
  ('DUA-A6K9-0NS', true, NULL, NOW()),
  ('DUA-A6Z8-CUZ', true, NULL, NOW()),
  ('DUA-A9P4-8OF', true, NULL, NOW()),
  ('DUA-ANPM-09K', true, NULL, NOW()),
  ('DUA-ARS7-7KY', true, NULL, NOW()),
  ('DUA-B6OP-QHH', true, NULL, NOW()),
  ('DUA-BW4V-JXR', true, NULL, NOW()),
  ('DUA-C024-TTY', true, NULL, NOW()),
  ('DUA-C19O-5ZH', true, NULL, NOW()),
  ('DUA-C50C-7E3', true, NULL, NOW()),
  ('DUA-CAQ3-W7F', true, NULL, NOW()),
  ('DUA-CFHR-Y0G', true, NULL, NOW()),
  ('DUA-CMHJ-I2O', true, NULL, NOW()),
  ('DUA-CY06-2LS', true, NULL, NOW()),
  ('DUA-D0CF-SCR', true, NULL, NOW()),
  ('DUA-D5U0-18P', true, NULL, NOW()),
  ('DUA-DT17-1M0', true, NULL, NOW()),
  ('DUA-EV4O-9SI', true, NULL, NOW()),
  ('DUA-FEDP-658', true, NULL, NOW()),
  ('DUA-G01Z-9W3', true, NULL, NOW()),
  ('DUA-G0WK-WTS', true, NULL, NOW()),
  ('DUA-G1OQ-GBM', true, NULL, NOW()),
  ('DUA-G2KS-I1T', true, NULL, NOW()),
  ('DUA-G4R1-47V', true, NULL, NOW()),
  ('DUA-G61V-3TG', true, NULL, NOW()),
  ('DUA-GHKP-C6K', true, NULL, NOW()),
  ('DUA-GK3Y-I7D', true, NULL, NOW()),
  ('DUA-GSV1-UOH', true, NULL, NOW()),
  ('DUA-GUF5-PDV', true, NULL, NOW()),
  ('DUA-H4Y4-071', true, NULL, NOW()),
  ('DUA-HGMM-03G', true, NULL, NOW()),
  ('DUA-HV3W-WWG', true, NULL, NOW()),
  ('DUA-HV59-SD7', true, NULL, NOW()),
  ('DUA-I15C-WQ1', true, NULL, NOW()),
  ('DUA-I2ZC-TNV', true, NULL, NOW()),
  ('DUA-I4CT-Z3T', true, NULL, NOW()),
  ('DUA-IABT-KH1', true, NULL, NOW()),
  ('DUA-IJ8D-4IP', true, NULL, NOW()),
  ('DUA-IJJ3-PIJ', true, NULL, NOW()),
  ('DUA-IQEJ-PFI', true, NULL, NOW()),
  ('DUA-J0MZ-XAU', true, NULL, NOW()),
  ('DUA-JCMO-9YY', true, NULL, NOW()),
  ('DUA-JHTA-5TZ', true, NULL, NOW()),
  ('DUA-JLKO-AC6', true, NULL, NOW()),
  ('DUA-JMTS-Z9R', true, NULL, NOW()),
  ('DUA-JQBE-J96', true, NULL, NOW()),
  ('DUA-JR59-I2S', true, NULL, NOW()),
  ('DUA-K7NJ-5PX', true, NULL, NOW()),
  ('DUA-K8LT-82Y', true, NULL, NOW()),
  ('DUA-KKOV-KQH', true, NULL, NOW()),
  ('DUA-KMAW-8ON', true, NULL, NOW()),
  ('DUA-KMK6-RX2', true, NULL, NOW()),
  ('DUA-KODG-MDF', true, NULL, NOW()),
  ('DUA-KX1R-D3C', true, NULL, NOW()),
  ('DUA-KX5S-JQQ', true, NULL, NOW()),
  ('DUA-L6BO-4B0', true, NULL, NOW()),
  ('DUA-LDOL-050', true, NULL, NOW()),
  ('DUA-LFAL-ALG', true, NULL, NOW()),
  ('DUA-LN7B-48W', true, NULL, NOW()),
  ('DUA-LQ7F-FGJ', true, NULL, NOW()),
  ('DUA-LSAO-PR3', true, NULL, NOW()),
  ('DUA-LYLX-9ZI', true, NULL, NOW()),
  ('DUA-M1GH-PTT', true, NULL, NOW()),
  ('DUA-M44O-D9K', true, NULL, NOW()),
  ('DUA-MBPW-KWG', true, NULL, NOW()),
  ('DUA-MDYI-R7Q', true, NULL, NOW()),
  ('DUA-MJEN-C5B', true, NULL, NOW()),
  ('DUA-MME0-M31', true, NULL, NOW()),
  ('DUA-NGRP-XZ6', true, NULL, NOW()),
  ('DUA-OARE-AZC', true, NULL, NOW()),
  ('DUA-OPKJ-8LA', true, NULL, NOW()),
  ('DUA-P8WP-MN7', true, NULL, NOW()),
  ('DUA-PZHP-S2N', true, NULL, NOW()),
  ('DUA-QJLO-HVZ', true, NULL, NOW()),
  ('DUA-QKEY-E5U', true, NULL, NOW()),
  ('DUA-QM1P-X67', true, NULL, NOW()),
  ('DUA-QZAD-6RF', true, NULL, NOW()),
  ('DUA-R063-IU3', true, NULL, NOW()),
  ('DUA-R4RX-SZB', true, NULL, NOW()),
  ('DUA-RBPV-F8M', true, NULL, NOW()),
  ('DUA-RJJZ-MT0', true, NULL, NOW()),
  ('DUA-RTXE-379', true, NULL, NOW()),
  ('DUA-RUPJ-EQB', true, NULL, NOW()),
  ('DUA-S14G-BNZ', true, NULL, NOW()),
  ('DUA-SJAF-W1P', true, NULL, NOW()),
  ('DUA-SRP4-83O', true, NULL, NOW()),
  ('DUA-SSJX-3Z4', true, NULL, NOW()),
  ('DUA-TC03-JY1', true, NULL, NOW()),
  ('DUA-TFIJ-0FX', true, NULL, NOW()),
  ('DUA-TGS0-Y7Y', true, NULL, NOW()),
  ('DUA-TNE1-3SF', true, NULL, NOW()),
  ('DUA-TNOV-ESK', true, NULL, NOW()),
  ('DUA-TS1F-5Y6', true, NULL, NOW()),
  ('DUA-U3JM-1SR', true, NULL, NOW()),
  ('DUA-U3TN-VO0', true, NULL, NOW()),
  ('DUA-UCIG-73K', true, NULL, NOW()),
  ('DUA-ULTZ-CKL', true, NULL, NOW()),
  ('DUA-UO24-VP7', true, NULL, NOW()),
  ('DUA-UOC1-4RF', true, NULL, NOW()),
  ('DUA-UY0X-K1P', true, NULL, NOW()),
  ('DUA-UZJU-YK6', true, NULL, NOW()),
  ('DUA-UZTM-2H6', true, NULL, NOW()),
  ('DUA-UZW8-RLU', true, NULL, NOW()),
  ('DUA-VOJW-TMI', true, NULL, NOW()),
  ('DUA-VQKE-FR0', true, NULL, NOW()),
  ('DUA-W4JP-Z4V', true, NULL, NOW()),
  ('DUA-W879-3OP', true, NULL, NOW()),
  ('DUA-X008-AK7', true, NULL, NOW()),
  ('DUA-X3MG-YZI', true, NULL, NOW()),
  ('DUA-X833-57P', true, NULL, NOW()),
  ('DUA-XA6X-NN2', true, NULL, NOW()),
  ('DUA-XBPL-6V9', true, NULL, NOW()),
  ('DUA-XDPN-1TB', true, NULL, NOW()),
  ('DUA-XF0E-KGW', true, NULL, NOW()),
  ('DUA-XHJR-A0W', true, NULL, NOW()),
  ('DUA-XOA5-RG7', true, NULL, NOW()),
  ('DUA-XWSJ-WDB', true, NULL, NOW()),
  ('DUA-Y4HF-WM1', true, NULL, NOW()),
  ('DUA-Y6QE-K7C', true, NULL, NOW()),
  ('DUA-YGHL-XTY', true, NULL, NOW()),
  ('DUA-YO21-12G', true, NULL, NOW()),
  ('DUA-YQWB-YYK', true, NULL, NOW()),
  ('DUA-YR0H-7PR', true, NULL, NOW()),
  ('DUA-Z4WU-GK6', true, NULL, NOW()),
  ('DUA-ZM22-E0Z', true, NULL, NOW()),
  ('DUA-ZPDM-KAF', true, NULL, NOW()),
  ('DUA-ZPGE-BQ8', true, NULL, NOW());

-- 3. Verificar inserção
SELECT COUNT(*) as total_codigos FROM public.invite_codes WHERE active = true;

-- 4. Ver primeiros 10 códigos
SELECT code, active, created_at FROM public.invite_codes ORDER BY code LIMIT 10;

-- ══════════════════════════════════════════════════════════════
-- ✅ EXECUÇÃO COMPLETA
-- 170 códigos prontos para uso!
-- ══════════════════════════════════════════════════════════════